config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/addjob', to: 'jobs#new'
  post '/addjob', to: 'jobs#new'
  


   resources :users, only:[:show, :create, :edit, :update]
   resources :categories, only: [:new, :create, :show, :index, :edit, :update]
   resources :jobs, only: [:show, :index, :create, :new, :edit, :update]
   resources :posts, except: [:destroy] do
     member do
      post 'vote'
     end

   resources :comments, only: [:create] do
     member do
      post 'vote'
    end
  end
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :votes, as: :voteable
  validates :body, presence: true

  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.user = current_user


		if @comment.save
          flash[:notice] = "Your comment was added"
          redirect_to post_path(@post)
    else
          render 'posts/show'
    end
  end

  def vote
    comment = Comment.find(params[:id])
    vote = Vote.create(voteable: comment, user: current_user, vote: params[:vote])

    if vote.valid?
      flash[:notice] = "Your vote was created"
    else
      flash[:error] = "Your can only vote a post once"
    end

    redirect_to :back
  end
end

app/views/comments/_comment.html.erb
  
<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' do %>
      <i class='icon-arrow-up'></i>
      <%end%>
    <br/>  
    <%= comment.total_votes %> votes
    <br/>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' do %>
      <i class='icon-arrow-down'></i>
    <%end%>

  </div>

  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post == true %>
    on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
      <p>
    <span class='quiet'> posted by </span> <%= link_to comment.user.username, user_path(comment.user) %>
    <small>at <%= display_datetime(comment.created_at) %></small>
    </p>
  </div>
</div>