config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/addjob', to: 'jobs#new'
  post '/addjob', to: 'jobs#new'
  


   resources :users, only:[:show, :create, :edit, :update]
   resources :categories, only: [:new, :create, :show, :index, :edit, :update]
   resources :jobs, only: [:show, :index, :create, :new, :edit, :update]
   resources :posts, except: [:destroy] do
     member do
      post 'vote'
     end

   resources :comments, only: [:create] do
     member do
      post 'vote'
    end
  end
end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

	validates :title, presence: true
	validates :description, presence: true

  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_admin, only: [:edit]

  
  def index
    @post = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to :back
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path
    else
      render :edit
    end
  end

  def vote
   @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])
     
     respond_to do |format|
       format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was created"
        else
          flash[:error] = "Your can only vote a post once"
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
    <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>
  <br/>
  <div class="control-group">
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline"){cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary')%>
  <% end %>

app/views/posts/_post.html.erb
<div class="row">
    <div class="span0 well text-center">
      <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
      <%= post.total_votes %> votes
      <br/>
      <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    </div>

    <div class='span8 well'>
    <%= render post.categories %>
      <h4><%=  post.title %></h4>
      <p><%= post.description %></p>
      <p>
        <span class='quiet'> posted by </span> <%=link_to post.user.username, user_path(post.user) %>
        <small>at <%= display_datetime(post.created_at) %></small>
      </p>
      <small>
        <span>
            <%= link_to("#{post.comments.size} comments",post_path(post)) %>
        </span>
        <span>
            (<%= link_to 'edit', edit_post_path(post) %>)
        </span>

      </small>
    </div>
  </div>
  

app/views/posts/edit.html.erb
<h4>Edit this post</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Notes' %>

<div class="alert alert-block">
  <button type="button" class="close" data-dismiss="alert">
  x</button>
  <h3> Welcome to DamnNotes </h3>
  DamnNotes is an online market for best notes. Our reseposibility is provide best notes to help student
  acheive their accedemic goal. We are currently purchasing great notes from all students in Minnesota, We 
  are also hiring students who want to make money by discover and recomment notes for us. Register for add 
  and vote for your course that need notes the most. We will sent you a copy of free notes if we have the course
  you added. And we will also select students randomly from those who vote and send them a copy too.  
  <br/>
    <h2><%= link_to "Join Us!", jobs_path %></h2>
</div>
<% @user = User.new   %>
<% @post.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>
<%= render 'shared/errors', obj: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <br/>
  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>
  <br/>
  <div class="control-group">
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline"){cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary')%>
  <% end %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post)%>]
  </p>
<% end %>


<%= render @post.categories %> 

<%= render 'shared/content_title', title: @post.title %>

<p>
<%= @post.description %>
</p>
<hr/>

<%if logged_in? %>
  <%= form_for [@post,@comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class="control-group">
      <%= f.label :body, "Leave a comment" %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit "Create a Comment", class: 'btn btn-primary' %>
  <% end %>
<%end%>

<h5>Comments: </h5>

<% @post.comments.each do |comment| %>
   <%= render 'comments/comment', comment: comment, show_post: false %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>

  $("#post_<%= @post.id %>_votes").html("<%= @post.total_votes %> votes");

<% else %>
  alert('you can only vote on a post once.')

<% end %>