config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/addjob', to: 'jobs#new'
  post '/addjob', to: 'jobs#new'
  


   resources :users, only:[:show, :create, :edit, :update]
   resources :categories, only: [:new, :create, :show, :index, :edit, :update]
   resources :jobs, only: [:show, :index, :create, :new, :edit, :update]
   resources :posts, except: [:destroy] do
     member do
      post 'vote'
     end

   resources :comments, only: [:create] do
     member do
      post 'vote'
    end
  end
end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_user, only:[:new,:create]
	before_action :set_category, only:[:edit, :update]
	before_action :require_admin, only:[:edit, :update]
	def new
      @category = Category.new
	end

	def show
	  @category = Category.find(params[:id])
	end

	def create
	  @category = Category.new(category_params)
	  if @category.save
	  	 flash[:notice] = "A new Category was created"
	  	 redirect_to root_path
	  else
	  	render :new
	  end
	end

	def edit
	end

	def update
		if @category.update(category_params)
      flash[:notice] = "The category was updated"
      redirect_to root_path
    else
      render :back
    end   
	end

	def index
		@category = Category.all
	end

	def category_params
      params.require(:category).permit(:name)
  end


  def set_category
    @category = Category.find(params[:id])
  end



end

app/views/categories/_category.html.erb
  <span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/edit.html.erb
<%= render 'shared/content_title', title: "Update Category" %>
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
<br/>
<%= f.submit(@category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary') %>
<% end %>

app/views/categories/index.html.erb
<%= @category.each do |category| %>
<%= category.name %>
</br>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
<br/>
<%= f.submit(@category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary') %>
<% end %>

app/views/categories/show.html.erb
<% header = link_to('All Notes', posts_path) + "&raquo; #{@category.name}".html_safe  %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>