config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/addjob', to: 'jobs#new'
  post '/addjob', to: 'jobs#new'
  


   resources :users, only:[:show, :create, :edit, :update]
   resources :categories, only: [:new, :create, :show, :index, :edit, :update]
   resources :jobs, only: [:show, :index, :create, :new, :edit, :update]
   resources :posts, except: [:destroy] do
     member do
      post 'vote'
     end

   resources :comments, only: [:create] do
     member do
      post 'vote'
    end
  end
end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "DamnNotes!", root_path, :class => 'brand' %>
  </li>
</ul>

  <div class="btn-group nav_item">
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      Categories 
      <span class='caret'></span>
    <% end %>
    <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end %>
      <li class="divider"></li>
      <li>
      	<%= link_to(new_category_path) do %>
      	<i class='icon-plus'></i>
      	  New Category
      	<% end %>
      </li>
    </ul>
  </div>
    

    <% if logged_in? %>  
      <div class='btn-group nav_item'>
        <%= link_to('',class: 'btn btn-small dropdown-toggle','data-toggle' => 'dropdown') do %>
        <%= current_user.username %>
        <span class='caret'></span>
       <% end %>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <i class='icon-pencil'></i>
              Edit Profile
              <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class='icon-user'></i>
              My Profile
              <% end %>
          </li>
          <li>
            <%= link_to logout_path(current_user) do %>
              <i class='icon-circle-arrow-left'></i>
              Log out!
              <% end %>
          </li>
        </ul>
    </div>

    <div class="nav_item">
      <%= link_to 'Add courses', new_post_path, class: 'btn btn-success' %>
    </div>

    <% else %>

    <div class="nav_item">
      <%= link_to 'Login', login_path, class: 'btn btn-success' %>
    </div>


    <div class="nav_item">
      <%= link_to 'Register', register_path, class: 'btn btn-success' %>
    </div>

   <% end %>
  

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DamnNotes</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>